name = "ai-grading-platform"
compatibility_date = "2025-04-03"

[build]
command = "npm run build"

[site]
bucket = ".next/static"

[[routes]]
pattern = "/*"
script = "worker.js"

[env.production]
workers_dev = true 